"""Verda transactional operations and snapshots

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-16 21:23:27.216488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_attempt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_attempt_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_attempt_fingerprint'), ['fingerprint'], unique=False)

    op.create_table('operation',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('endpoint', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('transaction_lock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('court_block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stadium_id', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('ends_at > starts_at', name='ck_block_interval'),
    sa.ForeignKeyConstraint(['stadium_id'], ['stadium.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('court_block', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_court_block_stadium_id'), ['stadium_id'], unique=False)

    op.create_table('notification_read',
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('notification_id', 'user_id')
    )
    op.create_table('stock_movement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_movement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_movement_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movement_product_id'), ['product_id'], unique=False)

    op.create_table('adjustment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('business_day', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['pos_session.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id'),
    sa.UniqueConstraint('session_id')
    )
    with op.batch_alter_table('adjustment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_adjustment_business_day'), ['business_day'], unique=False)

    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('debt_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('business_day', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("method IN ('cash','card')", name='ck_payment_method'),
    sa.ForeignKeyConstraint(['debt_id'], ['manual_debts.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['pos_session.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_business_day'), ['business_day'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_debt_id'), ['debt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_session_id'), ['session_id'], unique=False)

    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('before_values', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('after_values', sa.JSON(), nullable=True))

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('business_day', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('starts_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('ends_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('pricing_snapshot', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('previous_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('archived', sa.Boolean(), server_default='0', nullable=False))
        batch_op.alter_column('original_price',
               existing_type=sa.FLOAT(),
               type_=sa.BigInteger(),
               existing_nullable=False)
        batch_op.alter_column('discount_amount',
               existing_type=sa.FLOAT(),
               type_=sa.BigInteger(),
               existing_nullable=True)
        batch_op.alter_column('final_price',
               existing_type=sa.FLOAT(),
               type_=sa.BigInteger(),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_booking_external_booking_id'))
        batch_op.create_index(batch_op.f('ix_booking_business_day'), ['business_day'], unique=False)
        batch_op.create_index('ix_booking_court_interval', ['stadium_id', 'starts_at', 'ends_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_ends_at'), ['ends_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_reference'), ['reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_booking_starts_at'), ['starts_at'], unique=False)
        batch_op.drop_column('external_booking_id')
        batch_op.drop_column('sheet_sent_at')
        batch_op.drop_column('last_synced_at')
        batch_op.drop_column('sheet_last_error')
        batch_op.drop_column('external_status')
        batch_op.drop_column('sheet_sent')

    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voided', sa.Boolean(), server_default='0', nullable=False))

    with op.batch_alter_table('manual_debts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uq_manual_debts_session_id', ['session_id'])
        batch_op.create_foreign_key('fk_manual_debts_session_id', 'pos_session', ['session_id'], ['id'])
        batch_op.create_foreign_key('fk_manual_debts_created_by', 'user', ['created_by'], ['id'])

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scope', sa.String(length=40), nullable=True))

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('delivery_fee', sa.BigInteger(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('business_day', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('venue_snapshot', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('finalized_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('stock_restored', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('voided', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('archived', sa.Boolean(), server_default='0', nullable=False))
        batch_op.alter_column('total_price',
               existing_type=sa.FLOAT(),
               type_=sa.BigInteger(),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_order_business_day'), ['business_day'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_reference'), ['reference'], unique=True)
        batch_op.drop_column('sheet_last_error')
        batch_op.drop_column('sheet_sent')
        batch_op.drop_column('sheet_sent_at')

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('snapshot', sa.JSON(), nullable=True))
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               type_=sa.BigInteger(),
               existing_nullable=False)

    with op.batch_alter_table('pos_order', schema=None) as batch_op:
        batch_op.alter_column('total_price',
               existing_type=sa.FLOAT(),
               type_=sa.BigInteger(),
               existing_nullable=True)

    with op.batch_alter_table('pos_order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('snapshot', sa.JSON(), nullable=True))
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               type_=sa.BigInteger(),
               existing_nullable=False)

    with op.batch_alter_table('pos_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('business_day', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('occupancy_key', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('booking_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pricing_snapshot', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('venue_snapshot', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('location_snapshot', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('actual_seconds', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('billed_seconds', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('discount_kind', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('discount_value', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('finalized_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cashier_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('stock_restored', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('voided', sa.Boolean(), server_default='0', nullable=False))
        batch_op.alter_column('play_time_price',
               existing_type=sa.FLOAT(),
               type_=sa.BigInteger(),
               existing_nullable=True)
        batch_op.alter_column('auto_discount',
               existing_type=sa.FLOAT(),
               type_=sa.BigInteger(),
               existing_nullable=True)
        batch_op.alter_column('manual_discount',
               existing_type=sa.FLOAT(),
               type_=sa.BigInteger(),
               existing_nullable=True)
        batch_op.alter_column('total_amount',
               existing_type=sa.FLOAT(),
               type_=sa.BigInteger(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_pos_session_business_day'), ['business_day'], unique=False)
        batch_op.create_index(batch_op.f('ix_pos_session_finalized_at'), ['finalized_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_pos_session_reference'), ['reference'], unique=True)
        batch_op.create_unique_constraint('uq_pos_session_booking_id', ['booking_id'])
        batch_op.create_unique_constraint('uq_pos_session_occupancy_key', ['occupancy_key'])
        batch_op.create_foreign_key('fk_pos_session_cashier_id', 'user', ['cashier_id'], ['id'])
        batch_op.create_foreign_key('fk_pos_session_booking_id', 'booking', ['booking_id'], ['id'])

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('track_stock', sa.Boolean(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('low_stock_threshold', sa.Integer(), server_default='5', nullable=False))
        batch_op.add_column(sa.Column('featured', sa.Boolean(), server_default='0', nullable=False))

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('configured', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('demo_mode', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('default_language', sa.String(length=4), server_default='ku', nullable=False))
        batch_op.add_column(sa.Column('timezone', sa.String(length=80), server_default='Asia/Baghdad', nullable=False))
        batch_op.add_column(sa.Column('minimum_minutes', sa.Integer(), server_default='60', nullable=False))
        batch_op.add_column(sa.Column('rounding_minutes', sa.Integer(), server_default='60', nullable=False))
        batch_op.add_column(sa.Column('max_booking_hours', sa.Integer(), server_default='4', nullable=False))
        batch_op.add_column(sa.Column('booking_days_ahead', sa.Integer(), server_default='30', nullable=False))
        batch_op.add_column(sa.Column('delivery_enabled', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('delivery_fee', sa.BigInteger(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('directions_url', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('receipt_width', sa.Integer(), server_default='80', nullable=False))
        batch_op.add_column(sa.Column('auto_print', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('label_size', sa.String(length=20), server_default='50x30', nullable=False))
        batch_op.add_column(sa.Column('content', sa.JSON(), nullable=True))

    with op.batch_alter_table('stadium', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived', sa.Boolean(), server_default='0', nullable=False))
        batch_op.alter_column('price_per_hour',
               existing_type=sa.FLOAT(),
               type_=sa.BigInteger(),
               existing_nullable=True)

    with op.batch_alter_table('table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived', sa.Boolean(), server_default='0', nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permissions', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('session_version', sa.Integer(), server_default='1', nullable=False))

    op.execute(sa.text('INSERT INTO transaction_lock (id) VALUES (1)'))
    with op.batch_alter_table('product') as batch_op:
        batch_op.create_check_constraint('ck_product_stock', 'stock >= 0')
        batch_op.create_check_constraint('ck_product_price', 'price >= 0')
    with op.batch_alter_table('manual_debts') as batch_op:
        batch_op.create_check_constraint('ck_debt_balance', 'amount >= 0 AND paid_amount >= 0 AND paid_amount <= amount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('session_version')
        batch_op.drop_column('permissions')

    with op.batch_alter_table('table', schema=None) as batch_op:
        batch_op.drop_column('archived')

    with op.batch_alter_table('stadium', schema=None) as batch_op:
        batch_op.alter_column('price_per_hour',
               existing_type=sa.BigInteger(),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.drop_column('archived')

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('content')
        batch_op.drop_column('label_size')
        batch_op.drop_column('auto_print')
        batch_op.drop_column('receipt_width')
        batch_op.drop_column('directions_url')
        batch_op.drop_column('delivery_fee')
        batch_op.drop_column('delivery_enabled')
        batch_op.drop_column('booking_days_ahead')
        batch_op.drop_column('max_booking_hours')
        batch_op.drop_column('rounding_minutes')
        batch_op.drop_column('minimum_minutes')
        batch_op.drop_column('timezone')
        batch_op.drop_column('default_language')
        batch_op.drop_column('demo_mode')
        batch_op.drop_column('configured')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('featured')
        batch_op.drop_column('low_stock_threshold')
        batch_op.drop_column('track_stock')

    with op.batch_alter_table('pos_session', schema=None) as batch_op:
        batch_op.drop_constraint('fk_pos_session_booking_id', type_='foreignkey')
        batch_op.drop_constraint('fk_pos_session_cashier_id', type_='foreignkey')
        batch_op.drop_constraint('uq_pos_session_occupancy_key', type_='unique')
        batch_op.drop_constraint('uq_pos_session_booking_id', type_='unique')
        batch_op.drop_index(batch_op.f('ix_pos_session_reference'))
        batch_op.drop_index(batch_op.f('ix_pos_session_finalized_at'))
        batch_op.drop_index(batch_op.f('ix_pos_session_business_day'))
        batch_op.alter_column('total_amount',
               existing_type=sa.BigInteger(),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('manual_discount',
               existing_type=sa.BigInteger(),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('auto_discount',
               existing_type=sa.BigInteger(),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('play_time_price',
               existing_type=sa.BigInteger(),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.drop_column('voided')
        batch_op.drop_column('stock_restored')
        batch_op.drop_column('cashier_id')
        batch_op.drop_column('finalized_at')
        batch_op.drop_column('discount_value')
        batch_op.drop_column('discount_kind')
        batch_op.drop_column('billed_seconds')
        batch_op.drop_column('actual_seconds')
        batch_op.drop_column('location_snapshot')
        batch_op.drop_column('venue_snapshot')
        batch_op.drop_column('pricing_snapshot')
        batch_op.drop_column('booking_id')
        batch_op.drop_column('occupancy_key')
        batch_op.drop_column('business_day')
        batch_op.drop_column('reference')

    with op.batch_alter_table('pos_order_item', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.BigInteger(),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.drop_column('snapshot')

    with op.batch_alter_table('pos_order', schema=None) as batch_op:
        batch_op.alter_column('total_price',
               existing_type=sa.BigInteger(),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.BigInteger(),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.drop_column('snapshot')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sheet_sent_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('sheet_sent', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('sheet_last_error', sa.TEXT(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_order_reference'))
        batch_op.drop_index(batch_op.f('ix_order_business_day'))
        batch_op.alter_column('total_price',
               existing_type=sa.BigInteger(),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.drop_column('archived')
        batch_op.drop_column('voided')
        batch_op.drop_column('stock_restored')
        batch_op.drop_column('finalized_at')
        batch_op.drop_column('venue_snapshot')
        batch_op.drop_column('business_day')
        batch_op.drop_column('delivery_fee')
        batch_op.drop_column('reference')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_column('scope')

    with op.batch_alter_table('manual_debts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_manual_debts_created_by', type_='foreignkey')
        batch_op.drop_constraint('fk_manual_debts_session_id', type_='foreignkey')
        batch_op.drop_constraint('uq_manual_debts_session_id', type_='unique')
        batch_op.drop_column('created_by')
        batch_op.drop_column('session_id')

    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_column('voided')

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sheet_sent', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('external_status', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('sheet_last_error', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('last_synced_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('sheet_sent_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('external_booking_id', sa.VARCHAR(length=120), nullable=True))
        batch_op.drop_index(batch_op.f('ix_booking_starts_at'))
        batch_op.drop_index(batch_op.f('ix_booking_reference'))
        batch_op.drop_index(batch_op.f('ix_booking_ends_at'))
        batch_op.drop_index('ix_booking_court_interval')
        batch_op.drop_index(batch_op.f('ix_booking_business_day'))
        batch_op.create_index(batch_op.f('ix_booking_external_booking_id'), ['external_booking_id'], unique=False)
        batch_op.alter_column('final_price',
               existing_type=sa.BigInteger(),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('discount_amount',
               existing_type=sa.BigInteger(),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('original_price',
               existing_type=sa.BigInteger(),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.drop_column('archived')
        batch_op.drop_column('previous_status')
        batch_op.drop_column('pricing_snapshot')
        batch_op.drop_column('ends_at')
        batch_op.drop_column('starts_at')
        batch_op.drop_column('business_day')
        batch_op.drop_column('reference')

    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.drop_column('after_values')
        batch_op.drop_column('before_values')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_session_id'))
        batch_op.drop_index(batch_op.f('ix_payment_order_id'))
        batch_op.drop_index(batch_op.f('ix_payment_debt_id'))
        batch_op.drop_index(batch_op.f('ix_payment_created_at'))
        batch_op.drop_index(batch_op.f('ix_payment_business_day'))

    op.drop_table('payment')
    with op.batch_alter_table('adjustment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_adjustment_business_day'))

    op.drop_table('adjustment')
    with op.batch_alter_table('stock_movement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_movement_product_id'))
        batch_op.drop_index(batch_op.f('ix_stock_movement_created_at'))

    op.drop_table('stock_movement')
    op.drop_table('notification_read')
    with op.batch_alter_table('court_block', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_court_block_stadium_id'))

    op.drop_table('court_block')
    op.drop_table('transaction_lock')
    op.drop_table('operation')
    with op.batch_alter_table('login_attempt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_attempt_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_login_attempt_created_at'))

    op.drop_table('login_attempt')
    # ### end Alembic commands ###
