"""Track returned inventory cost adjustments

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-17 02:22:00.195026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adjustment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cogs_reversal', sa.BigInteger(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adjustment', schema=None) as batch_op:
        batch_op.drop_column('cogs_reversal')

    # ### end Alembic commands ###
